spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(C24pV/qP9PWFYmozqe26LtN20kFkkCZ7tmSBwMzzypqa0msH++csbAthFjjtxoU75Puz/w6Fe4EIvtQfRZaL7ulbH4SQ5A9hgj7x/TNmJcaJr852qzRmgmHGezZSy9ve)
    username: ENC(20Y47uqYwjIGJQ524+daLA==)
    password: ENC(RjZnNGDdbI+N9zS8Oqutfw==
  mail:
    host: smtp.naver.com
    port: 587
    username: ENC(+0FRyAzyYgR4Vr1fTJOP6gw+4lFteNoO)
    password: ENC(HubMnmDG9ea/TXHYSYGgNDR+ri+e395B)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ENC(wra9t3qoARQiOuWCRpj8Q/X+ZTRos0A9sxdJHxQRd6Y=)
            client-secret: ENC(9OamsH9KA6eqiVzjzCoS24CZvsGaaoIx)
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email, gender, birthday
            client-name: SongTest
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

upload:
  path: ENC(FAgRs+5Qv0/NJNe3WUe2BYk3ToSNSVV8FgyUsHutX4O3sLQOLxRvrC/YGHbblMrsRbGIy4YEEgY=)