spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(mNi/s9ugf4V8IDn2Y68bA/8IJjM2xmsHGXAl+vtFV3aIGfdl6R0yEdm5AEQvRk/JG+vDKTPoVX3BhsXCtheByzbY6GNbwbUwYK2+ZHZ9pKzbPor2oKTVuLCvwU36k1hw)
    username: ENC(23zb4jGeJ534RDnyz2XeDg==)
    password: ENC(O7YPSm7B08gfyf5R4NhR7A==)
  mail:
    host: smtp.naver.com
    port: 587
    username: ENC(poq266lZ4/XtbGdq+ARryMfeqrSzYjV2)
    password: ENC(QMIdDjkiCXT+pt4eHU0za0HIOQXYGEKW)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ENC(ryJfhjjhn/tbCSdxrlbOdiI8kVKiPjOd3H6+Y8A2N6c=)
            client-secret: ENC(D9+syEPiexr5YkiZDyW9sVoebR8qRv1g)
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email, gender, birthday
            client-name: Song
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

upload:
  path: ENC(okaQS4gH3ysw/xT/J0B5wZiulp/DGlNZSFh5siFPJFvPZk0Upga4X8AGR9R+v9OZvArrpQfF/0Q=)

logging:
  level:
    org:
      springframework:
        security: DEBUG
