spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(tee9Pyl3Q69JVbJPNswgNey/QxauIOIboT0/a8aIzfYx+QIqIqnqIt8jWSwhFBXSnblqntQ2QL7DqvqHTAcH+TwyhFQUrf8kaNLfwPUlkveI9GJtwvrGKFRlzgxBCI8p)
    username: ENC(18Qe93owdyrxejEV1I9pzA==)
    password: ENC(KZLi3obgueRnbXlMihrzlA==)
  mail:
    host: smtp.naver.com
    port: 587
    username: ENC(MFfFSoclBuum0BZt21c3prr2jmC/aMfq)
    password: ENC(hoaJJhnKMq7GUGDK0HTgPHynOYY9JaMc)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ENC(JdBMh81ONTxN6tJifd+yaEtqsafPrSb/n8/h9ofoAyA=)
            client-secret: ENC(x9jENnCUFVz47F0S80Ay7xEWk2868tBZ)
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email, gender, birthday
            client-name: SongTest
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

upload:
  path: ENC(Zx+hfsxTb+wK2BUfpZPWrulgQREkXkezduHIWT2JAprb7Jk0kZh/ZBzMyFQ7iB+srZIQvcDlKcE=)